### ISSUE TITLE
Third party dependencies in Core are a code smell.

### ISSUE THREAD

**Issue by Didza** [trevoirwilliams/HR.LeaveManagement.CleanArchitecture-dotnet5#1]
The implementation of auto mapper in the Core as Profiles brings a dependency of auto mapper into the core yet your core application should have no third party dependencies just pure C# code, and all third party dependencies added on the outer layer, as an adapter to the application and not in the core domain.

Whats your thoughts on this I may be way off but I think a high level module like the core, should not depend on a lower level module like auto mapper.

**Comment by trevoirwilliams** [comment]
Hello Didza,

Forgive me but, when you say **Core**, which project exactly are you referring to?
I ask becuase I don't have a project called Core and My AutoMapper and MediatR libraries are included in the Application Project.

The project defines the Handlers and Core application functions and assets (so I guess this is it). In this case, MediatR and AutoMapper would fall into the same code smell scenario if this was the case, as they are both third-party libraries. 

Generally speaking, some person may well see it as a code smell, and others might not. I am not going to say if it is wrong or right, because 50% of these decisions comes down to philosophy and and personal/project preference.

**Comment by Didza** [comment]
I think I focused more on the folders rather that the dependencies as per project. You are 100% right it will all come down to personal preference but the goal remains one, loose coupling and high extensibility.
